appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: OPQ04K5msB4SIRnlRlBgLsZxKfIiIzPgqkMaI7Pn1vA1t4Ax2Zx+fWgPbFxkgUkcx5W1QZmAoMMX6qv5SLMfWU3uuA3XvgpnJu+5/HozOYiPIb3C2Zb0qaAI69OeKOV9hmSiTa2r79NznFwwt0eHUYahfyOeLGWYZ7mOzoIWe0jzjFGqlwzPVp/od2Gajo0DQRTGihpZc9NO0qRKqGd0hVNWHCXeQ69nsekIJ1Uz8uLMBwsIJEvZYtMR+4HtEoLf/sIPXlUQM9VdZJRFRVtvttAzbAq4znFs+/Nfxp+WTd/DBpIikjPal6ucH+0TbhLGwaYNfmsRGDuuKsgHT+3+bIIPiFWv1X/THsCK/LTbo2lvdZcl7AvtnvdU3S1c33EycgFdQ8JGwHR2pbFMA8sRWFkTf+ZaZn3j3XJMyqPkPuUSnmW+qkbN12eS4013G2XHxbwS4P2YOx5f71fznmGRdrFtWPf3XLX7hahaoUFRrD0PZejHbamDEqU2F7fplIaPFibUb5b4o+++bmqjN4Xgt8h1IbjIpvWx3SgnOPqs+G270k/ekkXy+lXhU0IyPP3+42VOIA+z8FOcNQwJ1nTSqEg2W/bX7CTSF1NfhdUj44dsLKsuKorh5f+NdUbmHsWRIXn/UFAW4B/64S7TW8BPM2xaSM5WT14NuNXKklgYQ0w=
